### PR TITLE
feat: split off the current image in iv into a separate window (#2058)

### PR DESCRIPTION
**Pull request by antond-weta**
## Description

This change adds a menu item "Split off" under the menu "File" which creates a new window and initialises it with the currently displayed image. 

## Tests

I have tested the UI changes on Mac and linux, I don't have a Windows machine currently. 
No other functionality should be affected by this change.

## Checklist:

- [x] I have read the [contribution guidelines](https://github.com/AcademySoftwareFoundation/OpenImageIO/blob/master/CONTRIBUTING.md).
- [x] I have updated the documentation, if applicable.
- [x] I have ensured that the change is tested somewhere in the testsuite
  (adding new test cases if necessary).
- [x] If I added or modified a C++ API call, I have also amended the
  corresponding Python bindings (and if altering ImageBufAlgo functions, also
  exposed the new functionality as oiiotool options).
- [x] My code follows the prevailing code style of this project. If I haven't
  already run clang-format before submitting, I definitely will look at the CI
  test that runs clang-format and fix anything that it highlights as being
  nonconforming.

### CODE REVIEW

**Comment by antond-weta** [comment]
The new window gets initialised with the default settings. I'm not sure how much of the current window's viewer state we want to retain.

**Comment by lgritz** [comment]
Nice! Instead of "split off", I would suggest calling the menu item "Move to new window", that seems to be what the equivalent operation is called in some other apps I just randomly sampled (Firefox, Chrome, Obsidian).

**Review by lgritz — CHANGES_REQUESTED** [review]
I suggested a different name for the command, but other than that, this LGTM.

**Comment by antond-weta** [comment]
> I suggested a different name for the command, but other than that, this LGTM.

Thanks Larry, I have renamed the command.
There are currently some EasyCLA issues happening on our side, they are being chased with LFX.

**Review by lgritz — APPROVED** [review]
LGTM! Just awaiting CLA to merge.

Note that #2058 was an aggregation of many scattered issues. This suggestion for this feature originally came from #287, filed in 2012!

**Comment by lgritz** [comment]
Aha, your CLA is working now!

@antond-weta, there appear to be a couple very minor clang-format fixes needed. As soon as that's ready, we're definitely ready to merge this.

**Pull request merged**
